{{ if .Values.deployer.serviceAccount.enabled }}

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-deployer
  labels: {{ include "ccbc-tools.labels" . | nindent 4}}
  namespace: {{ .Release.namespace }}

{{ end }}
