# We may have to remove this and use crunchy minAvailable once the operator is upgraded
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hippo-ha-pdb
spec:
  minAvailable: {{ sub .Values.replicaCount 1 }}
  selector:
    matchLabels:
      postgres-operator.crunchydata.com/instance-set: {{ .Values.instances.name }}
