fullnameOverride: ccbc

replicaCount: 1

image:
  app:
    repository: ghcr.io/bcgov/conn-ccbc-portal/ccbc-app
    pullPolicy: IfNotPresent
    tag: 'sha-edc6e3632d91c91b7916d75aa68925779fe77b54' # The tag value must be passed in via the deploy script
    clientSecret: '' # clientSecret must be passed in via deploy script
  psql:
    repository: gcr.io/ggl-cas-storage/cas-postgres
    pullPolicy: IfNotPresent
    tag: '0.3.0'
  db:
    repository: ghcr.io/bcgov/conn-ccbc-portal/ccbc-db
    pullPolicy: IfNotPresent
    tag: 'sha-edc6e3632d91c91b7916d75aa68925779fe77b54' # The tag value must be passed in via the deploy script

app:
  port: '3000'
  probesPort: '9000'
  namespace: ''
  enableAnalytics: true
route:
  host: '' # The host value must be passed in via the deploy script

resources:
  app:
    requests:
      cpu: '40m'
      memory: '128Mi'
    limits:
      cpu: '120m'
      memory: '256Mi'
  psql:
    requests:
      cpu: '40m'
      memory: '128Mi'
    limits:
      cpu: '120m'
      memory: '256Mi'

deployer:
  namespace: '' # The namespace must be passed in via the deploy script
  serviceAccount:
    enabled: true

networkPolicies:
  enabled: true

db:
  name: ccbc
  appUser: ccbc_app
  ownerUser: ccbc
  readonlyUser: ccbc_readonly
  preInitCommand: ''
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

metabase:
  instanceName: ccbc-metabase
  namespace: '' # The value must be passed in via the deploy script

# Postgres Cluster resource values:
exporter:
  requests:
    cpu: 20m
    memory: 64Mi
  limits:
    cpu: 60m
    memory: 128Mi

instances:
  name: hippo-ha
  replicas: 3
  requests:
    cpu: 20m
    memory: 64Mi
  limits:
    cpu: 60m
    memory: 128Mi

replicaCertCopy:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 30m
    memory: 64Mi

dataVolumeClaimSpec:
  storage: 256Mi

pgbackrest:
  requests:
    cpu: 20m
    memory: 64Mi
  limits:
    cpu: 60m
    memory: 128Mi
  volume:
    storage: 64Mi
    storageClassName: netapp-file-backup
  repoHost:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 60m
      memory: 128Mi

pgBouncer:
  requests:
    cpu: 20m
    memory: 64Mi
  limits:
    cpu: 60m
    memory: 128Mi