secureRoute:
  wwwRoute:
    enable: true

resources:
  app:
    requests:
      cpu: 500m
      memory: '1Gi'
    limits:
      cpu: 500m
      memory: '1Gi'

pgBouncer:
  requests:
    cpu: 250m
    memory: 8Mi
  limits:
    cpu: 250m
    memory: 32Mi

instances:
  name: hippo-ha
  replicas: 3
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
