kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-metabase-access
  labels:
{{ include "ccbc.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.metabase.namespace }}
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: {{ .Values.metabase.instanceName }}
{{- if .Values.metabase.prodIngress.enable }}
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.metabase.prodNamespace }}
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: {{ .Values.metabase.instanceName }}
{{- end }}


