kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-metabase-access
  labels:
{{ include "ccbc.labels" . | indent 4}}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.metabase.namespace }}
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: {{ .Values.metabase.instanceName }}

{{- if .Values.metabase.prodIngress.enable }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-metabase-prod-ingress
  labels:
{{ include "ccbc.labels" . | indent 4}}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.metabase.prodNamespace }}
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: {{ .Values.metabase.instanceName }}
{{- end }}
