name: 'Run Jest tests'
description: 'Runs the CCBC app locally'
runs:
  using: composite
  steps:
    - name: run jest tests with coverage
      shell: bash
      working-directory: ./app
      run: yarn test --coverage
