{{ if .Values.linter.serviceAccount.enabled }}

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-linter
  labels: {{ include "ccbc-tools.labels" . | nindent 4}}
  namespace: {{ .Values.linter.namespace }}

{{ end }}
