name: Run CCBC end to end tests

env:
  PGPASSWORD: postgres
  PGUSER: postgres
  PGDATABASE: ccbc

on: [workflow_call]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run docker image
        shell: bash
        run: docker run -d -p 3000:3000 ghcr.io/bcgov/conn-ccbc-portal/ccbc-app:sha-${{ github.sha }}
      - name: run docker image
        shell: bash
        run: yarn test:e2e
        working-directory: ./app
