on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Sonarcloud Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: setup dev env
      uses: ./.github/actions/dev-env-setup
    - name: Run Jest tests
      working-directory: ./app
      run: yarn test --coverage
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: ./app
        args: >
          -Dsonar.organization=bcgov-sonarcloud
          -Dsonar.projectKey=bcgov_CONN-CCBC-portal
          -Dsonar.javascript.lcov.reportPaths=./app/coverage/lcov.info
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}